const videoData = [
  {
    id: 1,
    model: 'Plus',
    title: "FIRST LOOK! New Design - America's first 7ft Interior Van. (full tour)",
    thumbnail: 'assets/images/video-thumbnail-1.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/PCX4ejUiWrM?si=dwev2eIEGJh6J7_m" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Vancaskeys',
  },
  {
    id: 2,
    model: 'Lite',
    title: "Tour this 20-foot Class B ProMaster Dream! 2025 Noovo Lite Van with Adventure Pack | Off-Grid Ready!",
    thumbnail: 'assets/images/video-thumbnail-2.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/bu5gGYP4FDA?si=wjFXmhDwKShldy0t" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Sunshine State RVs',
  },
  {
    id: 3,
    model: 'Lite',
    title: "Van Tour - Noovo Lite | The most luxurious van!",
    thumbnail: 'assets/images/video-thumbnail-3.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/5TutHvo0yeA?si=Z_gGLwRVJQxKK6pb" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Neal & Britt',
  },
  {
    id: 4,
    model: 'Plus',
    title: "America’s 1st 7ft Interior Class B Camper Van! The Noovo Plus",
    thumbnail: 'assets/images/video-thumbnail-4.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/S0CIiIWLZcw?si=lEcFAksdCP2KPI2L" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Vancasikmys',
  },
  {
    id: 5,
    model: 'Pop',
    title: "Pop Top Tent Van Camper at its Finest",
    thumbnail: 'assets/images/video-thumbnail-5.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/SaANss9RJwY?si=Osf503RecF9NGwSw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Jarrod Tocci',
  },
  {
    id: 6,
    model: 'Pop',
    title: "Is this the BEST POP TOP Campervan on the Market (3 FULL VANS TOURS)",
    thumbnail: 'assets/images/video-thumbnail-6.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/qBnkyjKG44M?si=Vs7hZNj8F11xxtDN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Vancasikmys',
  },
  {
    id: 7,
    model: 'Plus',
    title: 'The BEST LUXURY Vans! | NOOVO FACTORY TOUR',
    thumbnail: 'assets/images/video-thumbnail-7.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/g7fFd_MylLM?si=YLjMTM4f2s9DlCtH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Nel & Britt',
  },
  {
    id: 8,
    model: 'Plus',
    title: 'Super High Roof NOOVO Plus: The Future of Promaster Camper Vans',
    thumbnail: 'assets/images/video-thumbnail-8.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/nZ9DjdARWA0?si=gieb3MV1YW5bJgkg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'StrangerPalooza',
  },
  {
    id: 9,
    model: 'Plus',
    title: '2024 Noovo Plus Class B Van | Ram ProMaster 3500 Chassis | First Super High Van Roof! | *FULL TOUR*',
    thumbnail: 'assets/images/video-thumbnail-9.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/xdbeFQsVpfY?si=c9xb5lQDcDJK_dzp" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Sunshine State RVs',
  },
  {
    id: 10,
    model: 'Plus',
    title: 'FIRST EVER Super High Roof Van TOUR (In America)',
    thumbnail: 'assets/images/video-thumbnail-10.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/3whqMTa4sFo?si=JUdC6h0XETPTn0PU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Jarrod Toock',
  },
  {
    id: 11,
    model: 'Lite',
    title: 'The First Super High Roof Promaster (7ft + Interior)',
    thumbnail: 'assets/images/video-thumbnail-11.jpg',
    embedCode: '<iframe width="560" height="315" src="https://www.youtube.com/embed/hMFK8GLgFH4?si=ynQGFhoBo38JJ1zK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    channel: 'Adventure Van Expo',
  },
];

export default videoData;